export { Home } from "./Home";
export { ErrorPage } from "./ErrorPage";
export { AboutUs } from "./AboutUs";
export { ContactForm } from "./ContactForm";
export { Store } from "./Store";
export { CartPage } from "./CartPage";
// export {AdminPage} from './AdminPage';
// export {UpdateProduct} from './UpdateProduct';
export { LoginPage } from "./LoginPage";
export { PaymmentSuccess } from "./PaymmentSuccess";
export { PaymmentFailed } from "./PaymmentFailed";
// export {AdminComments} from './AdminComments';
